spring:
  profiles:
    active: db, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.dingmj.bigmall.admin:  DEBUG
    com.dingmj.bigmall.litemall:  ERROR
