package com.dingmj.bigmall.db.dao;

import com.dingmj.bigmall.db.domain.BigmallAdmin;
import com.dingmj.bigmall.db.domain.BigmallAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BigmallAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    long countByExample(BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int deleteByExample(BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int insert(BigmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int insertSelective(BigmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    BigmallAdmin selectOneByExample(BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    BigmallAdmin selectOneByExampleSelective(@Param("example") BigmallAdminExample example, @Param("selective") BigmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    List<BigmallAdmin> selectByExampleSelective(@Param("example") BigmallAdminExample example, @Param("selective") BigmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    List<BigmallAdmin> selectByExample(BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    BigmallAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BigmallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    BigmallAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    BigmallAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BigmallAdmin record, @Param("example") BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BigmallAdmin record, @Param("example") BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BigmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BigmallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BigmallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}