package com.dingmj.bigmall.db.dao;

import com.dingmj.bigmall.db.domain.BigmallLog;
import com.dingmj.bigmall.db.domain.BigmallLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BigmallLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    long countByExample(BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int deleteByExample(BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int insert(BigmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int insertSelective(BigmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    BigmallLog selectOneByExample(BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    BigmallLog selectOneByExampleSelective(@Param("example") BigmallLogExample example, @Param("selective") BigmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    List<BigmallLog> selectByExampleSelective(@Param("example") BigmallLogExample example, @Param("selective") BigmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    List<BigmallLog> selectByExample(BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    BigmallLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BigmallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    BigmallLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    BigmallLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BigmallLog record, @Param("example") BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BigmallLog record, @Param("example") BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BigmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BigmallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BigmallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}