package com.dingmj.bigmall.db.dao;

import com.dingmj.bigmall.db.domain.BigmallBrand;
import com.dingmj.bigmall.db.domain.BigmallBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BigmallBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    long countByExample(BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int deleteByExample(BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int insert(BigmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int insertSelective(BigmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    BigmallBrand selectOneByExample(BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    BigmallBrand selectOneByExampleSelective(@Param("example") BigmallBrandExample example, @Param("selective") BigmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    List<BigmallBrand> selectByExampleSelective(@Param("example") BigmallBrandExample example, @Param("selective") BigmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    List<BigmallBrand> selectByExample(BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    BigmallBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BigmallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    BigmallBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    BigmallBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BigmallBrand record, @Param("example") BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BigmallBrand record, @Param("example") BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BigmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BigmallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BigmallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigmall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}